### ISSUE TITLE
Todo: Add CLI

### ISSUE THREAD

**Issue by good-idea** [sanctuarycomputer/sanity-graph-import#5]
- [ ] Add a `bin` field to package.json
- [ ] Set up bin script
- [ ] Get config arguments from environment variables:

      SANITY_IMPORT_SOURCE_PROJECTID=...
      SANITY_IMPORT_SOURCE_DATASET=...
      SANITY_IMPORT_DESTINATION_PROJECTID=...
      SANITY_IMPORT_DESTINATION_DATASET=...
      SANITY_IMPORT_DESTINATION_WRITE_TOKEN=...
      SANITY_IMPORT_INITIAL_QUERIES=/path/to/my/queries.js / .ts
      
- [ ] Update docs
